/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/archive': RouteRecordInfo<'/archive', '/archive', Record<never, never>, Record<never, never>>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/bugs': RouteRecordInfo<'/bugs', '/bugs', Record<never, never>, Record<never, never>>,
    '/interview/': RouteRecordInfo<'/interview/', '/interview', Record<never, never>, Record<never, never>>,
    '/interview/interview-questions': RouteRecordInfo<'/interview/interview-questions', '/interview/interview-questions', Record<never, never>, Record<never, never>>,
    '/interview/write-resume': RouteRecordInfo<'/interview/write-resume', '/interview/write-resume', Record<never, never>, Record<never, never>>,
    '/links': RouteRecordInfo<'/links', '/links', Record<never, never>, Record<never, never>>,
    '/nav': RouteRecordInfo<'/nav', '/nav', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/公开的api': RouteRecordInfo<'/notes/公开的api', '/notes/公开的api', Record<never, never>, Record<never, never>>,
    '/notes/Axios': RouteRecordInfo<'/notes/Axios', '/notes/Axios', Record<never, never>, Record<never, never>>,
    '/notes/common-code-snippets': RouteRecordInfo<'/notes/common-code-snippets', '/notes/common-code-snippets', Record<never, never>, Record<never, never>>,
    '/notes/git': RouteRecordInfo<'/notes/git', '/notes/git', Record<never, never>, Record<never, never>>,
    '/notes/git-tortoisegit': RouteRecordInfo<'/notes/git-tortoisegit', '/notes/git-tortoisegit', Record<never, never>, Record<never, never>>,
    '/notes/monorepo': RouteRecordInfo<'/notes/monorepo', '/notes/monorepo', Record<never, never>, Record<never, never>>,
    '/notes/npm': RouteRecordInfo<'/notes/npm', '/notes/npm', Record<never, never>, Record<never, never>>,
    '/notes/PicGo+腾讯COS+Typora搭建图床': RouteRecordInfo<'/notes/PicGo+腾讯COS+Typora搭建图床', '/notes/PicGo+腾讯COS+Typora搭建图床', Record<never, never>, Record<never, never>>,
    '/notes/programming-standard': RouteRecordInfo<'/notes/programming-standard', '/notes/programming-standard', Record<never, never>, Record<never, never>>,
    '/notes/typescript': RouteRecordInfo<'/notes/typescript', '/notes/typescript', Record<never, never>, Record<never, never>>,
    '/notes/Vue-Router': RouteRecordInfo<'/notes/Vue-Router', '/notes/Vue-Router', Record<never, never>, Record<never, never>>,
    '/notes/Vue常用的Api': RouteRecordInfo<'/notes/Vue常用的Api', '/notes/Vue常用的Api', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/博客迁移': RouteRecordInfo<'/posts/博客迁移', '/posts/博客迁移', Record<never, never>, Record<never, never>>,
    '/posts/使用Netlify自动化部署Vitepress': RouteRecordInfo<'/posts/使用Netlify自动化部署Vitepress', '/posts/使用Netlify自动化部署Vitepress', Record<never, never>, Record<never, never>>,
    '/posts/使用vercel自动化部署express项目': RouteRecordInfo<'/posts/使用vercel自动化部署express项目', '/posts/使用vercel自动化部署express项目', Record<never, never>, Record<never, never>>,
    '/posts/canvas-ecg': RouteRecordInfo<'/posts/canvas-ecg', '/posts/canvas-ecg', Record<never, never>, Record<never, never>>,
    '/posts/code-style-standard': RouteRecordInfo<'/posts/code-style-standard', '/posts/code-style-standard', Record<never, never>, Record<never, never>>,
    '/posts/code-style-standard-new': RouteRecordInfo<'/posts/code-style-standard-new', '/posts/code-style-standard-new', Record<never, never>, Record<never, never>>,
    '/posts/component-dev-environment': RouteRecordInfo<'/posts/component-dev-environment', '/posts/component-dev-environment', Record<never, never>, Record<never, never>>,
    '/posts/component-library-packaging': RouteRecordInfo<'/posts/component-library-packaging', '/posts/component-library-packaging', Record<never, never>, Record<never, never>>,
    '/posts/css-effects': RouteRecordInfo<'/posts/css-effects', '/posts/css-effects', Record<never, never>, Record<never, never>>,
    '/posts/custom-block-and-code': RouteRecordInfo<'/posts/custom-block-and-code', '/posts/custom-block-and-code', Record<never, never>, Record<never, never>>,
    '/posts/Electron+Vue3的远程打印项目': RouteRecordInfo<'/posts/Electron+Vue3的远程打印项目', '/posts/Electron+Vue3的远程打印项目', Record<never, never>, Record<never, never>>,
    '/posts/eslint-prettier-husky-commitlint-guide': RouteRecordInfo<'/posts/eslint-prettier-husky-commitlint-guide', '/posts/eslint-prettier-husky-commitlint-guide', Record<never, never>, Record<never, never>>,
    '/posts/express+ts+sequelize构建服务端': RouteRecordInfo<'/posts/express+ts+sequelize构建服务端', '/posts/express+ts+sequelize构建服务端', Record<never, never>, Record<never, never>>,
    '/posts/garbage-collection': RouteRecordInfo<'/posts/garbage-collection', '/posts/garbage-collection', Record<never, never>, Record<never, never>>,
    '/posts/module': RouteRecordInfo<'/posts/module', '/posts/module', Record<never, never>, Record<never, never>>,
    '/posts/package-manager': RouteRecordInfo<'/posts/package-manager', '/posts/package-manager', Record<never, never>, Record<never, never>>,
    '/posts/React快速入门': RouteRecordInfo<'/posts/React快速入门', '/posts/React快速入门', Record<never, never>, Record<never, never>>,
    '/posts/sharp-install-failed': RouteRecordInfo<'/posts/sharp-install-failed', '/posts/sharp-install-failed', Record<never, never>, Record<never, never>>,
    '/posts/sse-stream-solution': RouteRecordInfo<'/posts/sse-stream-solution', '/posts/sse-stream-solution', Record<never, never>, Record<never, never>>,
    '/posts/streaming-chart': RouteRecordInfo<'/posts/streaming-chart', '/posts/streaming-chart', Record<never, never>, Record<never, never>>,
    '/posts/typescript-types-packaging': RouteRecordInfo<'/posts/typescript-types-packaging', '/posts/typescript-types-packaging', Record<never, never>, Record<never, never>>,
    '/posts/vue-base': RouteRecordInfo<'/posts/vue-base', '/posts/vue-base', Record<never, never>, Record<never, never>>,
    '/posts/vue-diving-component': RouteRecordInfo<'/posts/vue-diving-component', '/posts/vue-diving-component', Record<never, never>, Record<never, never>>,
    '/todo': RouteRecordInfo<'/todo', '/todo', Record<never, never>, Record<never, never>>,
  }
}
